<table cellspacing="0" cellpadding="0" width="100%">
    <colgroup>
    <col width="33%"/>
    <col width="33%"/>
    <col width="33%"/>
    </colgroup>
    <thead>
        <tr>
            <th>Weekdays</th>
            <th>Saturday</th>
            <th class="orange">Sunday</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>     
        <tr>
            <td>0827</td>
            <td>0827</td>
            <td class="orange">1135</td>
        </tr>
        <tr>
            <td>0842</td>
            <td>0842</td>
            <td class="orange">1205</td>
        </tr>
        <tr>
            <td>0857</td>
            <td>0912</td>
            <td class="orange">--35</td>
        </tr>
        <tr>
            <td>0912</td>
            <td>0942</td>
            <td class="orange">--05</td>
        </tr>
        <tr>
            <td>0927</td>
            <td>1012</td>
            <td class="orange">1635</td>
        </tr>
        <tr>
            <td>0942</td>
            <td>1027</td>
            <td class="orange">1657</td>
        </tr>
        <tr>
            <td>--57</td>
            <td>1042</td>
        </tr>
        <tr>
            <td>--12</td>
            <td>--57</td>
        </tr>
        <tr>
            <td>--27</td>
            <td>--12</td>
        </tr>
        <tr>
            <td>--42</td>
            <td>--27</td>
        </tr>
        <tr>
            <td>1557</td>
            <td>--42</td>
        </tr>
        <tr>
            <td>1612</td>
            <td>1557</td>
        </tr>
        <tr>
            <td>1627</td>
            <td>1612</td>
        </tr>
        <tr>
            <td>1647</td>
            <td>1627</td>
        </tr>
        <tr>
            <td>1702</td>
            <td>1647</td>
        </tr>
        <tr>
            <td>1705</td>
            <td>1702</td>
        </tr>
        <tr>
            <td>1717</td>
            <td>1705</td>
        </tr>
        <tr>
            <td>1732</td>
            <td>1717</td>
        </tr>
        <tr>
            <td>1747</td>
            <td>1732</td>
        </tr>
        <tr>
            <td>1802</td>
            <td>1747</td>
        </tr>
        <tr>
            <td>1817</td>
            <td>1802</td>
        </tr>
        <tr>
            <td>1850</td>
            <td>1817</td>
        </tr>
        <tr>
            <td>1920</td>
            <td>1850</td>
        </tr>
        <tr>
            <td>1950</td>
            <td>1920</td>
        </tr>
        <tr>
            <td>2020</td>
            <td>1950</td>
        </tr>
        <tr>
            <td>2050</td>
            <td>2020</td>
        </tr>
        <tr>
            <td>2120</td>
            <td>2050</td>
        </tr>
        <tr>
            <td>2150</td>
            <td>2120</td>
        </tr>
        <tr>
            <td>2342</td>
            <td>2150</td>
        </tr>
        <tr>
            <td>0022</td>
            <td>2342</td>
        </tr>
        <tr>
        	<td></td>
            <td>0022</td>
        </tr>
    </tbody>
</table>
