<table cellspacing="0" cellpadding="0" width="100%">
    <colgroup>
    <col width="33%"/>
    <col width="33%"/>
    <col width="33%"/>
    </colgroup>
    <thead>
        <tr>
            <th>Weekdays</th>
            <th>Saturday</th>
            <th class="orange">Sunday</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>0835</td>
            <td>0835</td>
            <td class="orange">1153</td>
        </tr>
        <tr>
            <td>0850</td>
            <td>0850</td>
            <td class="orange">1223</td>
        </tr>
        <tr>
            <td>0853</td>
            <td>0905</td>
            <td class="orange">--53</td>
        </tr>
        <tr>
            <td>0905</td>
            <td>0920</td>
            <td class="orange">--23</td>
        </tr>
        <tr>
            <td>0912</td>
            <td>0935</td>
            <td class="orange">1653</td>
        </tr>
        <tr>
            <td>0920</td>
            <td>0950</td>
            <td class="orange">1708</td>
        </tr>
        <tr>
            <td>0927</td>
            <td>1005</td>
            <td class="orange">1733</td>
        </tr>
        <tr>
            <td>0935</td>
            <td>1012</td>
            <td class="orange">1753</td>
        </tr>
        <tr>
            <td>0942</td>
            <td>1020</td>
            <td class="orange">1818</td>
        </tr>
        <tr>
            <td>0950</td>
            <td>1027</td>
            <td class="orange">1843</td>
        </tr>
        <tr>
            <td>--57</td>
            <td>1035</td>
            <td class="orange">1943</td>
        </tr>
        <tr>
            <td>--05</td>
            <td>1042</td>
            <td class="orange">2043</td>
        </tr>
        <tr>
            <td>--12</td>
            <td>1050</td>
            <td></td>
        </tr>
        <tr>
            <td>--20</td>
            <td>--57</td>
        </tr>
        <tr>
            <td>--27</td>
            <td>--05</td>
        </tr>
        <tr>
            <td>--35</td>
            <td>--12</td>
        </tr>
        <tr>
            <td>--42</td>
            <td>--20</td>
        </tr>
        <tr>
            <td>--50</td>
            <td>--27</td>
        </tr>
        <tr>
            <td>1557</td>
            <td>--35</td>
        </tr>
        <tr>
            <td>1617</td>
            <td>--42</td>
        </tr>
        <tr>
            <td>1625</td>
            <td>--50</td>
        </tr>
        <tr>
            <td>1632</td>
            <td>1557</td>
        </tr>
        <tr>
            <td>1640</td>
            <td>1617</td>
        </tr>
        <tr>
            <td>1647</td>
            <td>1625</td>
        </tr>
        <tr>
            <td>1655</td>
            <td>1632</td>
        </tr>
        <tr>
            <td>1702</td>
            <td>1640</td>
        </tr>
        <tr>
            <td>1710</td>
            <td>1647</td>
        </tr>
        <tr>
            <td>1713</td>
            <td>1655</td>
        </tr>
        <tr>
            <td>1717</td>
            <td>1702</td>
        </tr>
        <tr>
            <td>1725</td>
            <td>1710</td>
        </tr>
        <tr>
            <td>1732</td>
            <td>1713</td>
        </tr>
        <tr>
            <td>1740</td>
            <td>1717</td>
        </tr>
        <tr>
            <td>1747</td>
            <td>1725</td>
        </tr>
        <tr>
            <td>1755</td>
            <td>1732</td>
        </tr>
        <tr>
            <td>1802</td>
            <td>1740</td>
        </tr>
        <tr>
            <td>1810</td>
            <td>1747</td>
        </tr>
        <tr>
            <td>1815</td>
            <td>1755</td>
        </tr>
        <tr>
            <td>1825</td>
            <td>1802</td>
        </tr>
        <tr>
            <td>1832</td>
            <td>1810</td>
        </tr>
        <tr>
            <td>1840</td>
            <td>1815</td>
        </tr>
        <tr>
            <td>1908</td>
            <td>1825</td>
        </tr>
        <tr>
            <td>1938</td>
            <td>1832</td>
        </tr>
        <tr>
            <td>2003</td>
            <td>1840</td>
        </tr>
        <tr>
            <td>2033</td>
            <td>1908</td>
        </tr>
        <tr>
            <td>2103</td>
            <td>1938</td>
        </tr>
        <tr>
            <td>2133</td>
            <td>2003</td>
        </tr>
        <tr>
            <td>2203</td>
            <td>2033</td>
        </tr>
        <tr>
            <td>2238</td>
            <td>2103</td>
        </tr>
        <tr>
            <td>2308</td>
            <td>2133</td>
        </tr>
        <tr>
            <td>2351</td>
            <td>2203</td>
        </tr>
        <tr>
            <td>0031</td>
            <td>2238</td>
        </tr>
        <tr>
        	<td></td>
            <td>2308</td>
        </tr>
        <tr>
        	<td></td>
            <td>2351</td>
        </tr>
        <tr>
        	<td></td>
            <td>0031</td>
        </tr>
    </tbody>
</table>
